# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Labtoolstcl 44-494}  -string {{ERROR: [Labtoolstcl 44-494] There is no active target available for server at localhost.
 Targets(s) ", jsn-Basys3-210183713960A" may be locked by another hw_server.}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Hanfu/OneDrive/EE2020/Lab/game/game.cache/wt [current_project]
set_property parent.project_path C:/Users/Hanfu/OneDrive/EE2020/Lab/game/game.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Hanfu/OneDrive/EE2020/Lab/game/game.srcs/sources_1/new/my_dff.v
  I:/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/clock_divider.v
  C:/Users/Hanfu/OneDrive/EE2020/Lab/game/game.srcs/sources_1/new/single_pulse.v
  C:/Users/Hanfu/OneDrive/EE2020/Lab/game/game.srcs/sources_1/new/blinky.v
  C:/Users/Hanfu/OneDrive/EE2020/Lab/game/game.srcs/sources_1/new/game.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Hanfu/OneDrive/EE2020/Lab/lab4/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Hanfu/OneDrive/EE2020/Lab/lab4/Basys3_Master.xdc]


synth_design -top game -part xc7a35tcpg236-1


write_checkpoint -force -noxdef game.dcp

catch { report_utilization -file game_utilization_synth.rpt -pb game_utilization_synth.pb }
